# Generated by cucumber-sinatra. (2012-06-13 21:46:34 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara-webkit'
require 'test/unit/assertions'
require 'database_cleaner'
require 'database_cleaner/cucumber'

Capybara.app = RCRApp
Capybara.javascript_driver = :webkit
DatabaseCleaner.strategy = :truncation

class RCRAppWorld
  include Capybara::DSL
  include Test::Unit::Assertions
end

World do
  RCRAppWorld.new
end

Before do
  @room_info = RoomInfo.new("site-config.yml")
  File.open('active.yml', 'r') {|f| @term = YAML::load(f)}
  DatabaseCleaner.start
end

After do
  DatabaseCleaner.clean
end
