# Generated by cucumber-sinatra. (2012-06-13 21:46:34 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RCRApp

class RCRAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RCRAppWorld.new
end
